# Generated by Django 6.1.1 on 2026-10-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='stock_resultante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('MERMA', 'Merma'), ('CORRECCION', 'Corrección')], max_length=20),
        ),
    ]
