# Generated by Django 5.2.17 on 2026-10-05 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_renombrar_der'),
        ('usuarios', '0002_alter_usuario_options_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(db_column='id_compra', primary_key=True, serialize=False)),
                ('proveedor', models.CharField(max_length=120)),
                ('fecha_compra', models.DateTimeField()),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(db_column='id_configuracion', primary_key=True, serialize=False)),
                ('maneja_caducidad', models.BooleanField(default=False)),
                ('maneja_promociones', models.BooleanField(default=False)),
                ('usa_codigo_barras', models.BooleanField(default=False)),
                ('alertas_activas', models.BooleanField(default=True)),
                ('vende_mayoreo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'Configuracion',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(db_column='id_detalle_compra', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
                'db_table': 'DetalleCompra',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(db_column='id_detalle_venta', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'db_table': 'DetalleVenta',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(db_column='id_negocio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('propietario', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'db_table': 'Negocio',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(db_column='id_promocion', primary_key=True, serialize=False)),
                ('tipo_promocion', models.CharField(choices=[('descuento_porcentaje', 'Descuento por porcentaje'), ('descuento_monto', 'Descuento por monto')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'db_table': 'Promocion',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(db_column='id_venta', primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.AlterModelOptions(
            name='alertastock',
            options={'verbose_name': 'Alerta de stock', 'verbose_name_plural': 'Alertas de stock'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'verbose_name': 'Movimiento de inventario', 'verbose_name_plural': 'Movimientos de inventario'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='alertastock',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='nivel_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='tipo_alerta',
            field=models.CharField(choices=[('stock_bajo', 'Stock bajo'), ('caducidad', 'Caducidad')], default='stock_bajo', max_length=20),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='alertastock',
            name='uuid_local',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo_merma',
            field=models.CharField(blank=True, choices=[('caducado', 'Caducado'), ('danado', 'Danado'), ('consumo_propio', 'Consumo propio'), ('devolucion_proveedor', 'Devolucion a proveedor'), ('otro', 'Otro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_resultante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_minima_mayoreo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='producto',
            name='piezas_por_empaque',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_mayoreo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('pieza', 'Pieza'), ('bolsa', 'Bolsa'), ('caja', 'Caja'), ('paquete', 'Paquete'), ('gramo', 'Gramo'), ('litro', 'Litro')], default='pieza', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertastock',
            name='id',
            field=models.AutoField(db_column='id_alerta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alertastock',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertastock',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(db_column='id_categoria', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='id',
            field=models.AutoField(db_column='id_movimiento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('merma', 'Merma'), ('correccion', 'Correccion')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(db_column='id_producto', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock_actual__gte', 0)), name='producto_stock_no_negativo'),
        ),
        migrations.AlterModelTable(
            name='alertastock',
            table='AlertaStock',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='Categoria',
        ),
        migrations.AlterModelTable(
            name='movimientoinventario',
            table='MovimientoInventario',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='compra',
            field=models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.compra'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='compra',
            field=models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.compra'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='usuario_admin',
            field=models.ForeignKey(db_column='id_usuario_admin', on_delete=django.db.models.deletion.PROTECT, related_name='negocios_administrados', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='negocio',
            field=models.OneToOneField(db_column='id_negocio', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='inventario.negocio'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='promociones', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.venta'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.venta'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(('stock_resultante__gte', 0)), name='movimiento_stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientoinventario',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('tipo_movimiento', 'correccion'), _negated=True), ('motivo__isnull', False), _connector='OR'), models.Q(models.Q(('tipo_movimiento', 'merma'), _negated=True), ('motivo_merma__isnull', False), _connector='OR'), models.Q(models.Q(('motivo_merma', 'otro'), _negated=True), ('motivo__isnull', False), _connector='OR')), name='chk_movimiento_motivo'),
        ),
    ]
