# Generated by Django 5.2.17 on 2026-10-05 21:43

import django.db.models.deletion
import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_conservar_historial'),
        ('usuarios', '0002_alter_usuario_options_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertastock',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='alertas', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='alertastock',
            name='uuid_local',
            field=models.CharField(default=inventario.models.generar_uuid_local, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria'),
        ),
    ]
