# Generated by Django 6.1.1 on 2026-10-06 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_alertastock_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.AddField(
            model_name='configuracion',
            name='dias_aviso_caducidad',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='hora_resumen',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='telefono_alertas',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tipo_precio',
            field=models.CharField(choices=[('normal', 'Normal'), ('mayoreo', 'Mayoreo'), ('promocion', 'Promoción'), ('editado', 'Editado')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_empaque',
            field=models.CharField(blank=True, choices=[('caja', 'Caja'), ('bolsa', 'Bolsa'), ('paquete', 'Paquete')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultimo_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('pieza', 'Pieza'), ('bolsa', 'Bolsa'), ('caja', 'Caja'), ('paquete', 'Paquete')], default='pieza', max_length=20),
        ),
        migrations.DeleteModel(
            name='AlertaStock',
        ),
    ]
