# Generated by Django 6.1.1 on 2026-10-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_contacto_alertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contenido_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_contenido',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'L')], max_length=3, null=True),
        ),
    ]
