# Generated by Django 6.1.1 on 2026-09-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('telefono_whatsapp', models.CharField(max_length=20)),
                ('rol', models.CharField(choices=[('propietario', 'Propietario'), ('encargado', 'Encargado')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
